<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_tiles_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'd_p_side_tiles':
      $field_tiles_side = $paragraph->get('field_d_p_st_tiles_side')->get(0);
      if ($field_tiles_side) {
        $tiles_side = $field_tiles_side->getValue();
        $variables['tiles_side'] = $tiles_side['value'];
      }
      $variables['#attached']['library'][] = 'd_p_tiles/masonry';
      $variables['#attached']['library'][] = 'd_p_side_tiles/d_p_side_tiles';
      break;
  }

  $variables['#attached']['library'][] = 'd_p_side_tiles/d_p_side_tiles';
}

/**
 * Implements hook_theme().
 */
function d_p_side_tiles_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_tiles' => [
      'base hook' => 'paragraph',
    ],
  ];
}
